name: bms
description: A specialized inventory management system for batteries.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Core & Authentication
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  cloud_functions: ^5.0.0
  firebase_storage: ^12.4.10 # Updated for null safety and version solving

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.0.0

  # UI & Charts
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  intl: ^0.20.2

  # Device Features
  image_picker: ^1.1.0
  image_cropper: ^8.0.2
  
  # Reporting
  pdf: ^3.10.0
  printing: ^5.12.0
  csv: ^6.0.0
  file_saver: ^0.3.1
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  diacritic: ^0.1.6
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  vector_graphics: ^1.1.19
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  version: ^3.0.2
  mobile_scanner: ^7.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/bms_square.png"
  min_sdk_android: 21 # set to min_sdk_version of your Android project
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/bms_square.png"
  adaptive_icon_foreground_inset: 0
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/bms_square.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/icons/bms_square.png"
    icon_size: 256

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/